// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cod3rboy/practice-cqrs/ent/patient"
	"github.com/google/uuid"
)

// Patient is the model entity for the Patient schema.
type Patient struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Ward holds the value of the "ward" field.
	Ward int `json:"ward,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Discharged holds the value of the "discharged" field.
	Discharged bool `json:"discharged,omitempty"`
	// CurrentVersion holds the value of the "current_version" field.
	CurrentVersion *int32 `json:"current_version,omitempty"`
	// ProjectedAtDatetime holds the value of the "projected_at_datetime" field.
	ProjectedAtDatetime time.Time `json:"projected_at_datetime,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Patient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case patient.FieldDischarged:
			values[i] = new(sql.NullBool)
		case patient.FieldWard, patient.FieldAge, patient.FieldCurrentVersion:
			values[i] = new(sql.NullInt64)
		case patient.FieldName:
			values[i] = new(sql.NullString)
		case patient.FieldProjectedAtDatetime:
			values[i] = new(sql.NullTime)
		case patient.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Patient fields.
func (pa *Patient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case patient.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pa.ID = *value
			}
		case patient.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pa.Name = value.String
			}
		case patient.FieldWard:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ward", values[i])
			} else if value.Valid {
				pa.Ward = int(value.Int64)
			}
		case patient.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				pa.Age = int(value.Int64)
			}
		case patient.FieldDischarged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field discharged", values[i])
			} else if value.Valid {
				pa.Discharged = value.Bool
			}
		case patient.FieldCurrentVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_version", values[i])
			} else if value.Valid {
				pa.CurrentVersion = new(int32)
				*pa.CurrentVersion = int32(value.Int64)
			}
		case patient.FieldProjectedAtDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field projected_at_datetime", values[i])
			} else if value.Valid {
				pa.ProjectedAtDatetime = value.Time
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Patient.
// This includes values selected through modifiers, order, etc.
func (pa *Patient) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// Update returns a builder for updating this Patient.
// Note that you need to call Patient.Unwrap() before calling this method if this Patient
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Patient) Update() *PatientUpdateOne {
	return NewPatientClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the Patient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *Patient) Unwrap() *Patient {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Patient is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Patient) String() string {
	var builder strings.Builder
	builder.WriteString("Patient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("name=")
	builder.WriteString(pa.Name)
	builder.WriteString(", ")
	builder.WriteString("ward=")
	builder.WriteString(fmt.Sprintf("%v", pa.Ward))
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", pa.Age))
	builder.WriteString(", ")
	builder.WriteString("discharged=")
	builder.WriteString(fmt.Sprintf("%v", pa.Discharged))
	builder.WriteString(", ")
	if v := pa.CurrentVersion; v != nil {
		builder.WriteString("current_version=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("projected_at_datetime=")
	builder.WriteString(pa.ProjectedAtDatetime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Patients is a parsable slice of Patient.
type Patients []*Patient
