// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)
